### ISSUE TITLE
`ord wallet inscriptions` only shows the first inscription for a UTXO, even if it contains multiple inscriptions

### ISSUE THREAD

**Issue by rot13maxi** [casey/ord#1012]
take a look at this output: https://signet.ordinals.com/output/6384224854a073cb31d42da4005ce8d93ea0d49555a286da513212f2d15510f3:0

It has three ord ranges. Two of them contain sats with inscriptions:

- https://signet.ordinals.com/sat/97676784921095
- https://signet.ordinals.com/sat/97676784911095

If I do `ord wallet inscriptions`, only the first one shows up:

```
% ./target/debug/ord --signet wallet inscriptions
e6717a460cfffc3f397b7b2882e00dc605264bbfdb75d55414fa6d6c69ad1b13	6384224854a073cb31d42da4005ce8d93ea0d49555a286da513212f2d15510f3:0:0
```

I would expect that both would be displayed.

Steps to reproduce:

1. Create two inscriptions in your wallet (using `ord transacribe`)
2. send both outputs containing the inscriptions to the same output. I did this by doing `bitcoin-cli sendall` to sweep my ordinals wallet to a new address

**Comment by casey** [comment]
Nice catch! We're currently being lazy and assuming that inscriptions always land on the first sat of the first output:

https://github.com/casey/ord/blob/aa80c1c044c850d7dbcbb8dde4d314e54acb7220/src/index/updater.rs#L406-L410

This was an okay assumption until now, because `ord wallet` will always send inscriptions to the first sat of the first output, but now that ne'er-do-wells such as yourself have merge multiple inscriptions into horrific Frankensteinian UTXOs, we'll have to fix this sooner rather than later!

**Comment by casey** [comment]
@rot13maxi This should be fixed as of #1108! Can you give this a shot using current master? You may have to rebuild the database, which is in `~/Library/Application Support/ord/signet/index.redb` if you're on a mac. (Somewhere in an XDG data dir on Linux.)

**Comment by rot13maxi** [comment]
```
% cargo run -- --signet wallet inscriptions
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/ord --signet wallet inscriptions`
ee6d7fb6adaad209707dc2eea6131849ce8fa8ad074257e46ba80c79dc64dd48	6384224854a073cb31d42da4005ce8d93ea0d49555a286da513212f2d15510f3:0:0
e6717a460cfffc3f397b7b2882e00dc605264bbfdb75d55414fa6d6c69ad1b13	6384224854a073cb31d42da4005ce8d93ea0d49555a286da513212f2d15510f3:0:89331
```

Looks great! Going to close this

**Comment by casey** [comment]
Nice!
