### ISSUE TITLE
Ordinal Addresses

### ISSUE THREAD

**Issue by casey** [casey/ord#1085]
Sending inscriptions to a non-ord wallet will likely result in them being lost. We could consider creating a special address type to avoid this, and only allow sending inscriptions to this address type. To implement this, we could  just use a unique bech32 prefix, like `ordbc1…` or `ord1…`.

**Comment by casey** [comment]
One thing I *don't* like about this is that it might make people think that ord addresses aren't just bitcoin addresses, when in fact they are.

**Comment by rot13maxi** [comment]
> Sending inscriptions to a non-ord wallet will likely result in them being lost.

why is that? why wouldnt they go to the recipient? (assuming they dont go to fees...)

**Comment by casey** [comment]
They would go to the recipient, but then if the recipient's wallet isn't `ord` (or another compatible wallet, or a wallet where the user can lock the output or do some other kind of manual coin control) they would probably lose the inscription when the recipient made a subsequent transaction.

**Comment by rot13maxi** [comment]
when you say "lose" you mean "accidentally spend", as opposed to "burn", right? like, you might accidentally spend some inscription that you meant to keep, not that the inscription would become invalid somehow

**Comment by casey** [comment]
Yup. The recipient's wallet might construct a transaction that sends the inscription to fees, or sends it to an outgoing address, instead of a change address.

**Comment by rot13maxi** [comment]
cool. That makes sense.

Of you wanted to avoid a new address scheme, maybe put another field in a BIP21 URI? have a "safe" mode for the ord wallet that only sends to URIs with an "ord_wallet=true" field or something.

I think its important that you're _able_ to send inscriptions to normal bitcoin wallets. It might be a bad idea if you want to keep that inscription, but I want to live in a world where someone gets some bitcoin from an exchange withdrawal or a p2p transaction and it turns out theres an inscription inside it!

**Comment by rot13maxi** [comment]
cool. That makes sense.

Of you wanted to avoid a new address scheme, maybe put another field in a BIP21 URI? have a "safe" mode for the ord wallet that only sends to URIs with an "ord_wallet=true" field or something.

I think its important that you're _able_ to send inscriptions to normal bitcoin wallets. It might be a bad idea if you want to keep that inscription, but I want to live in a world where someone gets some bitcoin from an exchange withdrawal or a p2p transaction and it turns out theres an inscription inside it!

**Comment by casey** [comment]
It's not really a whole new address scheme, fortunately, just a different human readable portion of existing bech32/bech32m addresses.

Good thought about a BIP21 URI, although URIs are more cumbersome than addresses. But if people want URIs for some reason, we can add a field.

We can add a `--allow-non-ord-addresses` or something, so that people can use vanilla addresses if they want to.

**Comment by casey** [comment]
Done in #1163! `ord wallet send` now generates ordinal addresses, and `ord wallet receive` sends to them. You can use `--cardinal` to generate normal bitcoin addresses, or bypass the check and send to them.

**Comment by casey** [comment]
> can we use the --cardinal flag to inscribe with a non-ord-address?

I don't understand what this means. What would the difference between inscribing with a cardinal and ordinal address be?
