### ISSUE TITLE
Enhanced Data Structures

### ISSUE THREAD

**Issue by vicariousdrama** [casey/ord#1523]
It would be beneficial if structures were well defined to make inscriptions more compact, and/or contain more metadata

The current inscription pattern is documented as follows

```
OP_FALSE
OP_IF
  OP_PUSH "ord"
  OP_1
  OP_PUSH "text/plain;charset=utf-8"
  OP_0
  OP_PUSH "Hello, world!"
OP_ENDIF
```

This leads with a header, in this case `ord` identifying the type of inscription. Documentation already states that others can be given for disambiguation.  I propose suffixing with a version (e.g. `ord2`) for enhanced structures, or something else entirely.

**Content Type**

The OP_1 code above indicates a type of metadata follows

The content type is the first push after the type of inscription.  Some size can be saved here if the content-type is expressed as a number when its a common type.  For example, using OP_2 to OP_16 could be mapped to mean the following most common types, while retaining OP_PUSH as the first instruction to denote a custom content-type.

- OP_2: application/x-gzip
- OP_3: application/pdf
- OP_4: application/zip
- OP_5: audio/midi
- OP_6: audio/mpeg
- OP_7: image/gif
- OP_8: image/jpeg
- OP_9: image/png
- OP_10: image/svg+xml
- OP_11: image/webp
- OP_12: text/html;charset=utf-8
- OP_13: text/plain;charset=utf-8
- OP_14: video/mp4
- OP_15: video/mpeg
- OP_16: video/webm

Before deciding on what content types to include this way, some analysis of counts of content-types used since inception should be done. 

**Additional Metadata**

I keep wishing that inscriptions had support for multiple items embedded, as well as given a name.  While a zip archive may be the most appropriate way to include multiple files, having at least a name is useful for web server explorers that want to provide a suggested filename to save as when doing an attachment type of Content-Disposition.  Without this, explorers can still fall back to either referencing by transaction identifier, or a short form of block number and transaction index.

I'd propose that additional fields like this would continue to be delineated by the OP_1, and then subsequent OP_PUSH.

For example:
```
OP_1
OP_PUSH "filename=somefile.css"
OP_1
OP_PUSH "author=Casey"
```

Similar to the content-type, we can use additional op codes to identify key metadata field names.  For example
```
OP_1
OP_2
OP_PUSH "somefile.css"
OP_1
OP_3
OP_PUSH "Casey"
```

Initial proposed meanings for OP_2 .. OP_16 op codes in the context of metadata

- OP_2: filename
- OP_3: author (for multiple authors, value to be comma delimited)
- OP_4: series name
- OP_5: description
- OP_6: tags (comma delimited values)
- OP_7: hash
- OP_8: signature

**Multiple Files**

At the end of all metadata, the OP_0 code continues to denote that the next block is the blob of data.  Compliant ones must make use of multiple OP_PUSH of appropriate size to chunk the bytes.  There would be no exceptions to being able to stream bytes into the end as long as the remainder bytes don't contain the 0x68 OP_ENDIF code.  

To indicate an additional file, an OP_1 code can begin the next content-type declaration

**Comment by tyjvazum** [comment]
I think these are great ideas, particularly using OP_2 through OP_16 to save some bytes on the content type field. That seems like a straightforward change. It helps to address criticism regarding blockchain bloat and might save some sats on the transaction fee.

It could also be extended to support more common content types by specifying behavior when there are two OP_2 through OP_16 opcodes used instead of a single opcode.

It sacrifices some human-readability, but I think that should be dealt with at the interface level, where necessary, anyway.

**Comment by vicariousdrama** [comment]
If we wanted to support a larger list of known content-types, then perhaps the structure would need more consideration.

One of the reasons I want additional metadata, in particular a standard for a hash (of the data), and signature (not yet sure of whether this should be of hash alone, or all the metadata) is to improve the notions of authenticity, as well as provide accountability to permit better automation of displaying content.  A public facing explorer could then opt in to only showing files that are signed from known contacts.  Similarly for users choosing to extract files for their own usage.  Relatedly, attribution to series and author is handy for NFT minded people.  

Maybe there needs to be other fields for edition number (e.g. 5) and set size (e.g. of 100) unless its fine to overload the filename "rock[5-100].jpg".  I had hoped that some of these would have embedded Exif data to denote this for the file types that support it, but that isn't the case in practice.

In considering ways to save space, reducing burden on node operators, and the fees of inscribers, there's room here as well to provide a standard for how to inscribe a parent artifact from which actual issues extend/inherit from to apply any custom coloring, edition number, and labeling.  

This would be useful for things like [rock](https://ordinals.com/inscription/e8ce0fcb238b377b3a6b9921333e26fbec5c5724c5bf6e783c3dcc1129794508i0), which was [repeated](https://ordinals.com/inscription/75604fd5f839e60edfd332a4a17e899afb47fcea0a1dbfced45c70d74a75d86ci0) and [recolored](https://ordinals.com/inscription/197e229722daf091d580db3a9ecacfd22b67b6628b9e5909c772cd06fd03d255i0) many times, or the Bitcoin Logo of which there were hundreds done around block 775097.  For those without any change to the data (a copy of the image) this could be done with a metadata field denoting the parent inscription (identified by txid, txin index, perhaps even file index in the inscription).  There may be ways to indicate recoloring (redefine palette?), rotating, seeding (for artifacts produce a different random image each time its viewed).

**Comment by casey** [comment]
Versioning is already handled by the "it's okay to be odd" rule, adopted from lightning. Adding a suffix to `ord` is awkward. we can add a version field when we have a concrete need for one. Other envelope protocols can use a different identifier.

Adding shorthands for specific content types only saves a few bytes, complicates the protocol, and introduces a moderation burden because everyone will ask the protocol to add a shorthand for their favored content type. Additionally, as far as efficiency goes, we have *much* bigger fish to fry. See #891 and #1521 for examples.

Free-form metadata which doesn't have a protocol-level function should be limited and only added when a clear need is established and a clear use-case and implementation is planned. Envelope headers should not become a free-for-all of arbitrary key-value pairs.

If free-form metadata is important, that can be done using multiple files on the same sat, which would allow users to add JSON metadata inscriptions. See #786.

A great place to start with additional metadata is #1005, adding a free-form text title to your inscription. This is simple, and can be easily added to both the inscription code, and the explorer, and is a great first step.

Much of the asks here are covered by other issues! I encourage you to think about specific use cases and benefits, instead of more general features, and to open focused issues related to those use cases and benefits. If those require adding metadata to the envelope protocol, great! Otherwise, if they can be supported another way, that's also great!
