### ISSUE TITLE
ord wallet create - code: -32601, message: "Method not found", data: None

### ISSUE THREAD

**Issue by sajshuai** [casey/ord#1643]
I install bitcoin-core by snap in ubuntu 22

`root@1:~/data/blockchain/bitcoin# bitcoin-core.cli getblockcount
775858
`
when I run 
`ord wallet create`

I got 
`error: JSON-RPC error: RPC error response: RpcError { code: -32601, message: "Method not found", data: None }`

**Comment by random9brat** [comment]
check bitcoin.conf and see if you got:

rpcuser=something
rpcpassword=something
rpcport=8332
txindex=1
rpcbind=127.0.0.1:8332

your connection to rpc is not working

**Comment by andrewtoth** [comment]
Do you have `disablewallet=1` in your `bitcoin.conf` file? You need to enable the wallet in order to use `ord`.
If not, then whatever you downloaded from snap either doesn't have the wallet compiled in, or is too old and doesn't support the commands that `ord` is using.
My recommendation would be to uninstall whatever you installed from snap and install Bitcoin Core from https://bitcoincore.org/en/download/.

**Comment by sajshuai** [comment]
> Do you have `disablewallet=1` in your `bitcoin.conf` file? You need to enable the wallet in order to use `ord`. If not, then whatever you downloaded from snap either doesn't have the wallet compiled in, or is too old and doesn't support the commands that `ord` is using. My recommendation would be to uninstall whatever you installed from snap and install Bitcoin Core from https://bitcoincore.org/en/download/.

Thank you very much, this solves my problem. I have never run bitcoin-core before, and there is no bitcoin.conf file after installation. I found one from the Internet, and his default disablewallet=1 caused me to fail all the time.
