### ISSUE TITLE
Private ordinals

### ISSUE THREAD

**Issue by casey** [casey/ord#167]
It would also be nice to define an extension for private ordinals. Some ideas:

- Private ordinals start at an arbitrary slot or satpoint

- Private ordinals don't use the default shuffling scheme. They use some keyed shuffling scheme where each private ordinal gets a different key, and if the attacker doesn't know the key, they won't know which output the private ordinal lands on in a transaction, and thus won't get any information by looking at patterns of transactions on-chain. The shuffling scheme could be keyed with the starting location of the ordinal, so all you need to know is the starting location to be able to track it, or it could be keyed with a secret known to all interested parties

Pros:
- Leak less information from viewing the chain. (Although still some, since the values and input/output orders for ordinal transactions are likely to be distinct.)
- Path from origin to current location is smaller, so less data to track
- Can use arbitrary shuffling schemes, and maybe users will come up with ones that are useful. (i.e. give all ordinals to first output, unless OP_RETURN exists, etc)

Cons:
- Hard to hold multiple private ordinals with different shuffling schemes in same output, since each uses different transfer rule
- Can't build public database that can perform fast lookups of arbitrary private ordinals
- Private ordinals aren't collectable

**Comment by VzxPLnHqr** [comment]
Thank you for further putting down some thoughts on private ordinals.

>Private ordinals don't use the default shuffling scheme. They use some keyed shuffling scheme where each private ordinal gets a different key, and if the attacker doesn't know the key, they won't know which output the private ordinal lands on in a transaction.

So, do you basically mean that we could (privately) agree that some particular satpoint S is, in effect, our "zero" in the sense that it would play the role played by the zeroth satoshi in your canonical ordering?

As a completely unrelated side-note which I would be happy to discuss further in a separate issue if you like, it is quite interesting to think about what happens if, rather than assign ordinal numbers to sats, we instead assign a sign `+1` or `-1` or `Heads` or `Tails` in some deterministic, yet random-looking way (using a hash function or some similar construction). Then it becomes possible to compute statistics pertaining to a given ordinal not only based on _which_ ordinals are in the utxo (according to your canonical ordering), but also some other _properties_ of the utxo (such as is, in the signing example, is the utxo net positive or net negative, or balanced?).  

On further thought, I suppose this mostly fits in with your "traits" concept, but the added complexity/tweak that the traits are dependent on the chosen ordering (naturally defaulting to your canonical ordering).

**Comment by casey** [comment]
> So, do you basically mean that we could (privately) agree that some particular satpoint S is, in effect, our "zero" in the sense that it would play the role played by the zeroth satoshi in your canonical ordering?

For private ordinals, we don't necessarily need to pick a zeroth satoshi. Every time we want a new private ordinal for something, we pick a new satpoint that one of us controls for the purpose. Since it's private, we don't need a globally unique identifier.

> As a completely unrelated side-note which I would be happy to discuss further in a separate issue if you like, it is quite interesting to think about what happens if, rather than assign ordinal numbers to sats, we instead assign a sign +1 or -1 or Heads or Tails in some deterministic, yet random-looking way (using a hash function or some similar construction). Then it becomes possible to compute statistics pertaining to a given utxo not only based on which ordinals are in the utxo (according to your canonical ordering), but also some other properties of the utxo (such as is, in the signing example, is the utxo net positive or net negative, or balanced?).

I have wacky ideas like this! Check out the [traits subcommand](https://github.com/casey/ord/blob/master/src/subcommand/traits.rs). It's just for fun, but it's a similar idea.

**Comment by casey** [comment]
I was thinking about private ordinals, and I actually think they're not particularly useful. I think what makes ordinals useful is precisely that they're globally unique and public, and once you want privacy, you don't need global uniqueness or publicness, and you're actually much better served by something like [RGB](https://rgb-org.github.io/).

Also, even if you have a private ID system, and a private shuffling system, you're still going to need to perform weird splitting transactions in order to move your private ordinals around, and those splitting transactions will look odd and leak data about what you're doing.

**Comment by VzxPLnHqr** [comment]
Thanks for the additional thoughts and exposition. I tend to agree with your conclusions regarding private ordinals.

>I have wacky ideas like this! Check out the [traits subcommand](https://github.com/casey/ord/blob/master/src/subcommand/traits.rs). It's just for fun, but it's a similar idea.

Yes, very intriguing!
