### ISSUE TITLE
Making Money

### ISSUE THREAD

**Issue by casey** [casey/ord#265]
- Drain exchange hot wallets of rare sats
- Provide liquidity to coinjoin pools and strip out rare sats

**Comment by jurraca** [comment]
Perhaps tangential, but might be interesting to monitor coinjoin transactions on chain for rare sats. Pools like Whirlpool have fairly high volume, and offer "free remixing", where users just leave their UTXOs there to be continually mixed for free. At most 2 transactions in a 5-UTXO coinjoin can be free remixes. Since they've been running for a fairly long time, it's likely there are some fun ordinals flowing through there.

**Comment by casey** [comment]
Great idea!
